[project]
name = "aye_finance_hr_bot___lightrag_enhanced"
version = "0.1.0"
description = "aye_finance_hr_bot___lightrag_enhanced using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[litellm,tools]==1.4.1",
]

[project.scripts]
aye_finance_hr_bot___lightrag_enhanced = "aye_finance_hr_bot___lightrag_enhanced.main:run"
run_crew = "aye_finance_hr_bot___lightrag_enhanced.main:run"
train = "aye_finance_hr_bot___lightrag_enhanced.main:train"
replay = "aye_finance_hr_bot___lightrag_enhanced.main:replay"
test = "aye_finance_hr_bot___lightrag_enhanced.main:test"
run_with_trigger = "aye_finance_hr_bot___lightrag_enhanced.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
